// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Cancel(arg1:number):Promise<void>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetQueue():Promise<Array<main.DownloadItem>>;

export function OpenFolderDialog():Promise<string>;

export function SetDownloadPath(arg1:string):Promise<void>;
