// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1:string,arg2:string,arg3:string):Promise<number>;
export function Cancel(arg1:number):Promise<void>;
export function SetDownloadPath(arg1:string):Promise<void>;
