// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {downloader} from '../models';

export function Cancel(arg1:number):Promise<void>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<number>;

export function ForceUpdateYtdlp():Promise<string>;

export function GetDownloadPath():Promise<string>;

export function GetQueue():Promise<Array<main.DownloadItem>>;

export function GetVideoInfo(arg1:string):Promise<downloader.VideoMetadata>;

export function GetWindowSize():Promise<Record<string, number>>;

export function IsAutostartEnabled():Promise<boolean>;

export function OpenDownloadedFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenFolderDialog():Promise<string>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetDownloadPath(arg1:string):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;
