// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function SetDownloadPath(arg1) {
  return window['go']['main']['App']['SetDownloadPath'](arg1);
}
